# Generated by Django 3.2.9 on 2021-12-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100, verbose_name='Заголовок H2')),
                ('about_description', models.CharField(max_length=300, verbose_name='Дополняющий текст')),
            ],
            options={
                'verbose_name': 'Секция о компаний',
            },
        ),
        migrations.CreateModel(
            name='AboutChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Почему мы?')),
            ],
            options={
                'verbose_name': 'Почему мы?',
            },
        ),
        migrations.CreateModel(
            name='FooterCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(max_length=200, verbose_name='Копирайт текст')),
            ],
            options={
                'verbose_name': 'Копирайт текст',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=100, verbose_name='Заголовок H1')),
                ('home_description', models.CharField(max_length=300, verbose_name='Дополняющий текст')),
            ],
            options={
                'verbose_name': 'Первая секция',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=200, verbose_name='Вопрос?')),
                ('question_description', models.CharField(max_length=500, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(max_length=2, verbose_name='Номер шага')),
                ('step_title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('step_description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаги',
            },
        ),
    ]
